spring:
  application:
    name: micro-service
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: ALWAYS
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          management:
            context-path: /actuator/health

server:
  port: 8081